Repository zencart/zencart, pull requests merged in 2020-05, with the labels that each got.

#3286 zc_install - Sync SQL updates (tested back to 1.5.1)
  zc_install/sql/install/mysql_zencart.sql
  zc_install/sql/updates/mysql_upgrade_zencart_156.sql
  zc_install/sql/updates/mysql_upgrade_zencart_157.sql
Labels: [Status] pending research by dev team

#3263 Updates to What's New
  docs/whatsnew_1.5.7.html
Labels: in progress

#3210 fixes countable error
  includes/modules/payment/square.php
Labels: [Issue Type] Confirmed Bug
