Repository zencart/zencart, pull requests merged in 2022-01, with the labels that each got.

#4431 Add notifier for category image
  includes/modules/category_row.php
Labels: v158

#4495 Fix incorrect call to get_audiences_list()
  admin/mail.php
Labels: Backport

#4481 Add trailing space after min
  includes/functions/functions_prices.php
Labels: Ready for Merge

#4532 Allow (new style) COD defs to be loaded without error
  admin/modules.php
  includes/classes/ResourceLoaders/ArraysLanguageLoader.php
  includes/classes/ResourceLoaders/CatalogArraysLanguageLoader.php
  includes/classes/ResourceLoaders/LanguageLoader.php
  includes/languages/english/modules/payment/lang.cod.php
  includes/languages/english/responsive_classic/index.php
  includes/languages/english/responsive_classic/lang.index.php
  includes/modules/payment/cod.php
Labels: Ready for Merge

#4530 add a common search form; fix missing closing tag
  admin/featured.php
  admin/includes/functions/html_output.php
  admin/specials.php
Labels: Ready for Merge

#4544 More de-duping of admin language defs
  admin/attributes_controller.php
  admin/downloads_manager.php
  admin/featured.php
  admin/geo_zones.php
  admin/includes/languages/english/lang.admin_account.php
  admin/includes/languages/english/lang.admin_activity.php
  admin/includes/languages/english/lang.admin_page_registration.php
  admin/includes/languages/english/lang.attributes_controller.php
  admin/includes/languages/english/lang.banner_manager.php
  admin/includes/languages/english/lang.banner_statistics.php
  admin/includes/languages/english/lang.configuration.php
  admin/includes/languages/english/lang.countries.php
  admin/includes/languages/english/lang.coupon_admin_export.php
  admin/includes/languages/english/lang.developers_tool_kit.php
  admin/includes/languages/english/lang.downloads_manager.php
  admin/includes/languages/english/lang.featured.php
  admin/includes/languages/english/lang.geo_zones.php
  admin/includes/languages/english/lang.gv_queue.php
  admin/includes/languages/english/lang.index.php
  admin/includes/languages/english/lang.invoice.php
  admin/includes/languages/english/lang.layout_controller.php
  admin/includes/languages/english/lang.login.php
  admin/includes/languages/english/lang.manufacturers.php
  admin/includes/languages/english/lang.modules.php
  admin/includes/languages/english/lang.music_genre.php
  admin/includes/languages/english/lang.newsletters.php
  admin/includes/languages/english/lang.option_name.php
  admin/includes/languages/english/lang.option_values.php
  admin/includes/languages/english/lang.options_name_manager.php
  admin/includes/languages/english/lang.options_values_manager.php
  admin/includes/languages/english/lang.orders.php
  admin/includes/languages/english/lang.orders_status.php
  admin/includes/languages/english/lang.packingslip.php
  admin/includes/languages/english/lang.product.php
  admin/includes/languages/english/lang.product_types.php
  admin/includes/languages/english/lang.products_price_manager.php
  admin/includes/languages/english/lang.products_to_categories.php
  admin/includes/languages/english/lang.profiles.php
  admin/includes/languages/english/lang.record_artists.php
  admin/includes/languages/english/lang.record_company.php
  admin/includes/languages/english/lang.salemaker.php
  admin/includes/languages/english/lang.salemaker_info.php
  admin/includes/languages/english/lang.salemaker_popup.php
  admin/includes/languages/english/lang.specials.php
  admin/includes/languages/english/lang.sqlpatch.php
  admin/includes/languages/english/lang.stats_customers.php
  admin/includes/languages/english/lang.stats_products_lowstock.php
  admin/includes/languages/english/lang.stats_products_purchased.php
  admin/includes/languages/english/lang.stats_products_viewed.php
  admin/includes/languages/english/lang.store_manager.php
  admin/includes/languages/english/lang.users.php
  admin/includes/languages/english/lang.whos_online.php
  admin/includes/languages/english/lang.zones.php
  admin/includes/languages/english/modules/newsletters/lang.newsletter.php
  admin/includes/languages/lang.english.php
  admin/options_name_manager.php
  admin/options_values_manager.php
  admin/products_price_manager.php
  admin/specials.php
  admin/stats_products_viewed.php
Labels: Ready for Merge

#4552 Fixes #4287, Handle categories returned by search
  admin/category_product_listing.php
  includes/functions/functions_prices.php
Labels: Ready for Merge

#4559 Remove config settings related to Tell a Friend
  zc_install/sql/updates/mysql_upgrade_zencart_158.sql
Labels: Ready for Merge

#4564 Fixes layout of featured add by product id page
  admin/featured.php
Labels: Ready for Merge

#4565 Broken layout on add special by id page
  admin/specials.php
Labels: Ready for Merge

#4486 Include Plugins in Search?
  admin/developers_tool_kit.php
  admin/includes/languages/english/developers_tool_kit.php
Labels: Ready for Merge

#4373 reduce queries required by zen_get_show_product_switch
  includes/classes/ProductConfigurationSwitch.php
  includes/modules/pages/product_info/main_template_vars.php
  includes/templates/responsive_classic/templates/tpl_modules_products_new_listing.php
  includes/templates/template_default/templates/tpl_modules_products_new_listing.php
Labels: Ready for Merge

#4580 Properly position extra customer fields created by NOTIFY_ADMIN_CUSTOMERS_CUSTOMER_EDIT
  admin/customers.php
Labels: Ready for Merge

#4581 NOTIFY_ADMIN_ORDERS_DEFAULT_ACTION should pass action just like NOTIFY_ADMIN_ORDER_PREDISPLAY_HOOK does
  admin/orders.php
Labels: Ready for Merge
