Repository zencart/zencart, pull requests merged in 2024-05, with the labels that each got.

#6429 Required for downloadable products
  includes/modules/payment/paypalwpp.php
Labels: 2.0.x

#6424 allow further get parameters when resetting product status
  admin/category_product_listing.php
Labels: 2.1.x

#6284 Hide empty zone field when appropriate, in setup wizard
  admin/index_setup_wizard.php
Labels: 2.1.x

#6363 Show pass last changed date in admin users
  admin/includes/functions/admin_access.php
  admin/includes/languages/english/lang.users.php
  admin/users.php
Labels: 2.1.x

#6451 Notifier to insert "More Information" and "Important Links" sidebox links
  includes/modules/sideboxes/ezpages.php
  includes/modules/sideboxes/more_information.php
Labels: 2.0.x

#6457 Correcting misplaced `</div>` tags ...
  includes/templates/responsive_classic/templates/tpl_document_general_info_display.php
  includes/templates/responsive_classic/templates/tpl_document_product_info_display.php
  includes/templates/responsive_classic/templates/tpl_product_free_shipping_info_display.php
  includes/templates/responsive_classic/templates/tpl_product_info_display.php
  includes/templates/responsive_classic/templates/tpl_product_music_info_display.php
Labels: 2.0.x

#6458 More useful starter text for accessibility page
  includes/languages/english/html_includes/define_accessibility.php
Labels: 2.0.x

#6455 Split order IP whois links
  admin/orders.php
Labels: 2.0.x

#6453 Add notifier hook to admin dashboard to allow custom widgets
  admin/index_dashboard.php
Labels: 2.0.x

#6462 Enable zc_plugins to provide AJAX content
  ajax.php
Labels: 2.0.x

#6463 PageLoader should use FileSystem for file exists
  includes/classes/ResourceLoaders/PageLoader.php
Labels: 2.0.x

#6456 Provide additional script helpers for encapsulated plugin mgmt
  includes/classes/PluginSupport/ScriptedInstallHelpers.php
  includes/classes/PluginSupport/ScriptedInstaller.php
  includes/classes/PluginSupport/ScriptedInstallerFactory.php
  zc_plugins/DisplayLogs/v3.0.2/Installer/ScriptedInstaller.php
Labels: 2.0.x

#6466 Structure zones like other shipping modules
  includes/modules/shipping/zones.php
Labels: 2.1.x

#6471 Make allowance for null products model
  admin/products_price_manager.php
  admin/specials.php
  includes/classes/CouponValidation.php
  includes/classes/shopping_cart.php
  includes/functions/functions_prices.php
  includes/functions/functions_products.php
  includes/modules/order_total/ot_gv.php
Labels: 2.0.2

#6370 Product class
  includes/classes/Product.php
  includes/classes/shopping_cart.php
  includes/functions/functions_products.php
  includes/modules/also_purchased_products.php
  includes/modules/featured_products.php
  includes/modules/new_products.php
  includes/modules/pages/document_general_info/header_php.php
  includes/modules/pages/document_general_info/main_template_vars.php
  includes/modules/pages/document_product_info/header_php.php
  includes/modules/pages/document_product_info/main_template_vars.php
  includes/modules/pages/product_free_shipping_info/header_php.php
  includes/modules/pages/product_free_shipping_info/main_template_vars.php
  includes/modules/pages/product_info/header_php.php
  includes/modules/pages/product_info/main_template_vars.php
  includes/modules/pages/product_music_info/header_php.php
  includes/modules/pages/product_music_info/main_template_vars.php
  includes/modules/product_listing.php
  includes/modules/responsive_classic/product_listing.php
  includes/modules/sideboxes/best_sellers.php
  includes/modules/specials_index.php
  includes/modules/upcoming_products.php
  includes/psr4Autoload.php
  includes/templates/responsive_classic/sideboxes/tpl_reviews_random.php
  includes/templates/template_default/sideboxes/tpl_featured.php
  includes/templates/template_default/sideboxes/tpl_reviews_random.php
  includes/templates/template_default/sideboxes/tpl_specials.php
  includes/templates/template_default/sideboxes/tpl_whats_new.php
Labels: 2.1.x

#6480 Correct storefront auto-load of zc_plugin classes
  includes/classes/InitSystem.php
Labels: 2.0.2

#6484 Fix GV_FAQ page
  includes/templates/template_default/templates/tpl_gv_faq_default.php
Labels: 2.0.2

#6493 Enable zc_plugin `extra_definitions` to be overridden by templates
  includes/classes/ResourceLoaders/CatalogArraysLanguageLoader.php
Labels: 2.0.2

#6500 Possible realpath returns false
  ajax.php
Labels: 2.0.2

#6488 Add switch for legacy "_" additional_image matching bypass
  includes/modules/additional_images.php
  zc_install/sql/install/mysql_zencart.sql
  zc_install/sql/updates/mysql_upgrade_zencart_210.sql
Labels: 2.1.x
